apiVersion: batch/v1
kind: Job
metadata:
  name: $SERVICE_NAME
spec:
  template:
    spec:
      containers:
      - name: kubectl
        image: nexus.wisers.com.cn/devops/kubectl:1.25.3
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Asia/Shanghai
        command:
        - bash
        - -c
        - kubectl rollout restart deployment/dma-translate-service
      restartPolicy: Never




